# Generated by Django 5.0.4 on 2024-05-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
